//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Il2CppDumper.Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FileResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Il2CppDumper.Files.FileResources", typeof(FileResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #pragma once
        ///
        ///#include &lt;string&gt;
        ///#include &lt;vector&gt;
        ///#include &lt;stdexcept&gt;
        ///
        ///#include &quot;methods.h&quot;
        ///
        ///namespace mods_api::classes {
        ///
        ///    class Il2CppClassLoader {
        ///    private:
        ///        const std::string className;
        ///        methods::M_Il2CppClass *il2CppClass = nullptr;
        ///
        ///    protected:
        ///        const std::string classNamespace;
        ///
        ///        inline virtual methods::M_Il2CppClass *getClassInternal() {
        ///            return methods::getIl2CppClass(classNamespace, className);
        ///        }
        ///
        ///    public:
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        public static string classes {
            get {
                return ResourceManager.GetString("classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #pragma once            
        ///
        ///#include &quot;il2cpp.h&quot;
        ///
        ///namespace mods_api::common_unity_types {
        ///
        ///    // primitives
        ///    using un_bool   = int8_t;
        ///    using un_char   = uint16_t;
        ///    using un_sbyte  = int8_t;
        ///    using un_byte   = uint8_t;
        ///    using un_short  = int16_t;
        ///    using un_ushort = uint16_t;
        ///    using un_int    = int32_t;
        ///    using un_uint   = uint32_t;
        ///    using un_long   = int64_t;
        ///    using un_ulong  = uint64_t;
        ///    using un_float  = float;
        ///    using un_double = double;
        ///
        ///    // types  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string common_unity_types {
            get {
                return ResourceManager.GetString("common_unity_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #pragma once
        ///
        ///#include &lt;string&gt;
        ///
        ///namespace mods_api::methods {
        ///
        ///    struct M_Il2CppClass;
        ///    struct M_Il2CppStaticFieldInfo;
        ///
        ///    M_Il2CppClass *getIl2CppClass(
        ///        const std::string &amp;classNamespace,
        ///        const std::string &amp;className
        ///    );
        ///
        ///    M_Il2CppClass *getIl2CppNestedClass(
        ///        M_Il2CppClass *containerClass,
        ///        const std::string &amp;nestedClassName
        ///    );
        ///
        ///    int32_t getIl2CppInstanceFieldOffset(
        ///        M_Il2CppClass *il2CppClass,
        ///        const std::string &amp;field [rest of string was truncated]&quot;;.
        /// </summary>
        public static string methods {
            get {
                return ResourceManager.GetString("methods", resourceCulture);
            }
        }
    }
}
